# Generated by Django 4.2.5 on 2024-01-07 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Source2',
            new_name='Mechine',
        ),
    ]
